### ISSUE TITLE
Similarity to the "ducks" pattern?

### ISSUE THREAD

**Issue by markerikson** [convoyinc/redux-interactions#5]
The description sounds a bit like https://github.com/erikras/ducks-modular-redux .  Thoughts on similarities or differences?

**Comment by nevir** [comment]
It seems to be almost identical.  Differences:

* Action types are formatted differently `module:TYPE`
* The reducer isn't the `default` export, but instead an export named `reducer`.
  * I like the default export that ducks does; but since we're leveraging decorators; not seeing a way of pulling that off
* In practice: we treat the reducer as optional.  We have several interactions files (modules) that are just collections of thunked action creators w/o any reducer logic
